Revert "vcu-ctrl-sw : Updated SRCREV for 2025.2_3355"
This reverts commit 50f7cb287da36de20a84cd57a7e0a2822118c271.

Causes a build failure in libvcu-omxil:

  module/ROIMngr.cpp:11:10: fatal error: lib_common/RoundUp.h: No such file or directory
    11 | #include "lib_common/RoundUp.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.