embeddedsw-source: Use allarch.bbclass
Run task do_create_spdx failed

  ERROR: mc:zynqmp-zcu102-sdt-full-cortexa53-fsbl:embeddedsw-source-2025.2-2025.2+git-r0 do_create_spdx: Could not find a static SPDX document named static-embeddedsw-source-2025.2

According to [1]:

  Converts the recipe to use allarch.bbclass. This is necessary because
  SSTATE_PKGARCH is set to "allarch" based on if allarch is inherited or
  not. If it is not, SSTATE_PKGARCH has the value "all", which means any
  data written out based on it cannot be found (because "all" is not in
  SSTATE_ARCHS)

[1] https://git.openembedded.org/openembedded-core/commit/?id=bd04d43100df64c0d638750af664cdcde7f06411

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Message-ID: <20260415145644.3811446-2-mark.hatle@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>