zephyr-kernel-src: Fix SRC_URI parse errors
Fix below SRC_URI parse errors.

ERROR: /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-zephyr/meta-zephyr-core/recipes-kernel/zephyr-kernel/zephyr-http-client.bb: Unable to get checksum for zephyr-http-client SRC_URI entry 0001-4.3.0-x86-fix-efi-binary-generation-issue-in-cross-compila.patch: file could not be found

Add FILESEXTRAPATHS:prepend to zephyr-kernel-src-4.3.0.inc
so that BitBake can locate the patch file.

AI-Generated: GitHub Copilot (Claude Sonnet 4.6)

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260319050407.1595770-7-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>