device-tree: Add support for mbv SDT build
Add support for mbv SDT build which fixes parse errors.

ERROR: Nothing PROVIDES 'virtual/dtb' (but /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/meta/recipes-core/images/core-image-minimal.bb DEPENDS on or otherwise requires it)
device-tree PROVIDES virtual/dtb but was skipped: incompatible with machine mbv64-sp701-sdt (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'virtual/dtb']

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260127002516.3850870-3-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>