esw: Fix asufw configure errors
Below asufw do_configure errors are observed while building asufw.

ERROR: mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:xilstandalone-2025.1+git-r0 do_configure: ExecutionError('/scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/run.do_configure.944430', 1, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/log.do_configure.944430
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-core/newlib/libgloss_git.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-core/newlib/newlib_git.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/cmake/cmake-native_3.28.3.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/gcc/gcc-cross_13.3.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/gcc/gcc-runtime_13.3.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/gcc/libgcc_13.3.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/../meta-virtualization/recipes-kernel/lopper/lopper_git.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/ninja/ninja_1.11.1.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/python/python3-dtc_1.7.0.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/python/python3-pyyaml_6.0.1.bb:do_populate_sysroot', 'mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:virtual:native:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/meta/recipes-devtools/python/python3_3.12.9.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['device-tree', 'sdt-artifacts', 'gettext-minimal-native', 'libgloss', 'newlib', 'binutils-cross-riscv32', 'cmake-native', 'gcc-cross-riscv32', 'gcc-runtime', 'libgcc', 'libtool-native', 'm4-native', 'quilt-native', 'texinfo-dummy-native', 'python3-humanfriendly-native', 'libyaml-native', 'lopper-native', 'util-linux-libuuid-native', 'python3-anytree-native', 'openssl-native', 'expat-native', 'ncurses-native', 'zlib-native', 'flex-native', 'gnu-config-native', 'libedit-native', 'make-native', 'ninja-native', 'patch-native', 'perl-native', 'pkgconfig-native', 'pseudo-native', 'python3-build-native', 'python3-cython-native', 'python3-dtc-native', 'python3-flit-core-native', 'python3-installer-native', 'python3-packaging-native', 'python3-pip-native', 'python3-pyparsing-native', 'python3-pyproject-hooks-native', 'python3-pyyaml-native', 'python3-ruamel-yaml-native', 'python3-setuptools-scm-native', 'python3-setuptools-native', 'python3-six-native', 'python3-tomli-native', 'python3-typing-extensions-native', 'python3-wheel-native', 'python3-native', 'swig-native', 'bzip2-native', 'libnsl2-native', 'libtirpc-native', 'unzip-native', 'xz-native', 'zstd-native', 'dtc-native', 'attr-native', 'gdbm-native', 'gmp-native', 'libffi-native', 'libmpc-native', 'libpcre2-native', 'mpfr-native', 're2c-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| -- The ASM compiler identification is GNU
| -- Found assembler: /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/recipe-sysroot-native/usr/bin/riscv32-xilinx-elf/riscv32-xilinx-elf-gcc
| -- Configuring done (0.1s)
| CMake Error at CMakeLists.txt:79 (add_library):
|   Cannot find source file:
|
|     xmicroblaze_g.c
|
|   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
|   .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
|   .f95 .f03 .hip .ispc
|
|
| CMake Error at CMakeLists.txt:79 (add_library):
|   No SOURCES given to target: xilstandalone
|
|
| CMake Generate step failed.  Build files cannot be regenerated correctly.
| WARNING: /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/run.do_configure.944430:182 exit 1 from 'cmake -G 'Ninja' -DCMAKE_MAKE_PROGRAM=ninja $oecmake_sitefile /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/build//lib/bsp/standalone/src/ -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DPYTHON_EXECUTABLE:PATH=/scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/recipe-sysroot-native/usr/bin/python3-native/python3 -DPython_EXECUTABLE:PATH=/scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/recipe-sysroot-native/usr/bin/python3-native/python3 -DPython3_EXECUTABLE:PATH=/scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/recipe-sysroot-native/usr/bin/python3-native/python3 -DLIB_SUFFIX= -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/toolchain.cmake -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DYOCTO=ON -Wno-dev'
| WARNING: Backtrace (BB generated script):
| 	#1: cmake_do_configure, /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/run.do_configure.944430, line 182
| 	#2: do_configure, /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/run.do_configure.944430, line 161
| 	#3: main, /scratch/sandeep/yocto/2025.1/yp-bc/build-versal2/tmp-versal2-vek385-sdt-seg-microblaze-riscv-asu/work/riscv32nf-xilinx-elf/xilstandalone/2025.1+git/temp/run.do_configure.944430, line 200
ERROR: Task (mc:versal2-vek385-sdt-seg-microblaze-riscv-asu:/scratch/sandeep/yocto/2025.1/yp-bc/sources/poky/../meta-xilinx/meta-xilinx-standalone-sdt/recipes-libraries/embeddedsw/xilstandalone_2025.1.bb:do_configure) failed with exit code '1'

This is due to wrong CMAKE_SYSTEM_PROCESSOR is set for asufw, Hence add
asu machinee check along with microblaze* DEFAULTTUNES.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>