meta-xilinx-core: cve-update-nvd2-native: Backport fixes
  From: Peter Marko <peter.marko@siemens.com>
  Date: Fri, 28 Mar 2025 16:48:20 +0100
  Subject: [PATCH] cve-update-nvd2-native: handle missing vulnStatus

  There is a new CVE which is missing vulnStatus field:
  https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2025-2682

  This leads to:
  File: '<snip>/poky/meta/recipes-core/meta/cve-update-nvd2-native.bb', lineno: 336, function: update_db
       0332:
       0333:    accessVector = None
       0334:    vectorString = None
       0335:    cveId = elt['cve']['id']
   *** 0336:    if elt['cve']['vulnStatus'] ==  "Rejected":
       0337:        c = conn.cursor()
       0338:        c.execute("delete from PRODUCTS where ID = ?;", [cveId])
       0339:        c.execute("delete from NVD where ID = ?;", [cveId])
       0340:        c.close()
  Exception: KeyError: 'vulnStatus'

  (From OE-Core rev: 2f242f2a269bb18aab703f685e27f9c3ba761db8)

  Signed-off-by: Peter Marko <peter.marko@siemens.com>
  Signed-off-by: Steve Sakoman <steve@sakoman.com>

  From: Peter Marko <peter.marko@siemens.com>
  Date: Mon, 7 Apr 2025 11:35:57 +0200
  Subject: [PATCH] cve-update-nvd2-native: add workaround for json5 style list

  NVD responses changed to an invalid json between:
  * April 5, 2025 at 3:03:44 AM GMT+2
  * April 5, 2025 at 4:19:48 AM GMT+2

  The last response is since then in format
  {
    "resultsPerPage": 625,
    "startIndex": 288000,
    "totalResults": 288625,
    "format": "NVD_CVE",
    "version": "2.0",
    "timestamp": "2025-04-07T07:17:17.534",
    "vulnerabilities": [
      {...},
      ...
      {...},
    ]
  }

  Json does not allow trailing , in responses, that is json5 format.
  So cve-update-nvd2-native do_Fetch task fails with log backtrace ending:

  ...
  File: '/builds/ccp/meta-siemens/projects/ccp/../../poky/meta/recipes-core/meta/cve-update-nvd2-native.bb', lineno: 234, function: update_db_file
       0230:            if raw_data is None:
       0231:                # We haven't managed to download data
       0232:                return False
       0233:
   *** 0234:            data = json.loads(raw_data)
       0235:
       0236:            index = data["startIndex"]
       0237:            total = data["totalResults"]
       0238:            per_page = data["resultsPerPage"]
  ...
  File: '/usr/lib/python3.11/json/decoder.py', lineno: 355, function: raw_decode
       0351:        """
       0352:        try:
       0353:            obj, end = self.scan_once(s, idx)
       0354:        except StopIteration as err:
   *** 0355:            raise JSONDecodeError("Expecting value", s, err.value) from None
       0356:        return obj, end
  Exception: json.decoder.JSONDecodeError: Expecting value: line 1 column 1442633 (char 1442632)
  ...

  There was no announcement about json format of API v2.0 by nvd.
  Also this happens only if whole database is queried (database update is
  fine, even when multiple pages as queried).
  And lastly it's only the cve list, all other lists inside are fine.
  So this looks like a bug in NVD 2.0 introduced with some update.

  Patch this with simple character deletion for now and let's monitor the
  situation and possibly switch to json5 in the future.
  Note that there is no native json5 support in python, we'd have to use
  one of external libraries for it.

  Signed-off-by: Peter Marko <peter.marko@siemens.com>

Signed-off-by: Mark Hatle <mark.hatle@amd.com>