Revert "xlnx-embeddedsw : Updated SRCREV for 2026.1_1611"
This reverts commit d1431e3226628321d0826f4dbb555499bbfd2b9d.

| /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/git/lib/sw_services/xilplmi/src/versal_2ve_2vm/xplmi_asu_cmd.c:42:10: fatal error: xocp_asufw.h: No such file or directory
|    42 | #include "xocp_asufw.h"
|       |          ^~~~~~~~~~~~~~
| compilation terminated.

 CMakeFiles/xilplmi.dir/common/server/xplmi_generic.c.obj.d -o CMakeFiles/xilplmi.dir/common/server/xplmi_generic.c.obj -c /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/git/lib/sw_services/xilplmi/src/common/server/xplmi_generic.c
| ninja: build stopped: subcommand failed.
|
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/temp/run.do_compile.1564493:159 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build '/scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/build' "$@" -- ${EXTRA_OECMAKE_BUILD}'
| WARNING: Backtrace (BB generated script):
| 	#1: cmake_runcmake_build, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/temp/run.do_compile.1564493, line 159
| 	#2: cmake_do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/temp/run.do_compile.1564493, line 153
| 	#3: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/temp/run.do_compile.1564493, line 148
| 	#4: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-versal2/tmp-versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc/work/microblazeel-v10.0-bs-cmp-re-mh-div-xilinx-elf/xilplmi/2026.1+git/temp/run.do_compile.1564493, line 172
ERROR: Task (mc:versal-2ve-2vm-vek385-revb-sdt-seg-microblaze-pmc:/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-standalone-sdt/recipes-libraries/embeddedsw/xilplmi_2026.1.bb:do_compile) failed with exit code '1'

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-Id: <20260210232730.2218585-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>