microblaze-v-generic: Set default UBOOT_MACHINE
Set default UBOOT_MACHINE for riscv32 and riscv64 arch. Without setting
these UBOOT_MACHINE microblaze-v SDT machine fails with below parse
errors.

ERROR: Nothing PROVIDES 'virtual/bootloader'
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
edk2-firmware PROVIDES virtual/bootloader but was skipped: incompatible with machine mbv64-sp701-sdt (not in COMPATIBLE_MACHINE)
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
u-boot-xlnx-imgrcvry PROVIDES virtual/bootloader but was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-xlnx, not u-boot-xlnx-imgrcvry
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
u-boot-xlnx PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the mbv64-sp701-sdt machine configuration.
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'virtual/bootloader']

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260127002516.3850870-2-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>