embeddedsw-source: Fix EXTERNALSRC build issue
Using EXTERNALSRC for embeddedsw fails to build with below errors.

ERROR: Task do_copy_shared_src in /scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-standalone/recipes-bsp/embeddedsw/plm-firmware_2025.1.bb depends upon non-existent task do_patch in /scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-standalone/recipes-bsp/embeddedsw/embeddedsw-source_2025.1.bb
ERROR: Command execution failed: 1

This is due to when we inherit externalsrc bbclass it will override
"do_patch do_unpack do_fetch" tasks and *-firmware recipe
"do_copy_shared_src" task depends on embeddedsw-source do_patch which
causes issue with EXTERNALSRC build method.

Hence add do_configure task for EXTERNALSRC build method and make
*-firmware recipe "do_copy_shared_src" depends task depends on
embeddedsw-source do_configure instead of do_patch task.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>