gstreamer1.0-omx: Add patch to fix build errors
Add patch to fix build errors.

DEBUG: Executing shell function do_compile
[1/2] aarch64-basecamp-linux-gcc -mcpu=cortex-a72.cortex-a53+crc -mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot -Iomx/libgstomx.so.p -Iomx -I../git/subprojects/gst-omx/omx -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/vcu2-omx-il -I. -I../git/subprojects/gst-omx -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/gstreamer-1.0 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/orc-0.4 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/glib-2.0 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/lib/glib-2.0/include -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/lib/gstreamer-1.0/include -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Winit-self -Wmissing-include-dirs -Wno-multichar -Wvla -Wpointer-arith -Wundef -Wmissing-prototypes -Wold-style-definition -Waggregate-return -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/git/subprojects/gst-omx=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/git/subprojects/gst-omx=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/build=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/build=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot= -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot= -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot-native= -fPIC -pthread -DHAVE_CONFIG_H -DGST_USE_UNSTABLE_API -MD -MQ omx/libgstomx.so.p/gstomxh265enc.c.o -MF omx/libgstomx.so.p/gstomxh265enc.c.o.d -o omx/libgstomx.so.p/gstomxh265enc.c.o -c ../git/subprojects/gst-omx/omx/gstomxh265enc.c
FAILED: omx/libgstomx.so.p/gstomxh265enc.c.o
aarch64-basecamp-linux-gcc -mcpu=cortex-a72.cortex-a53+crc -mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot -Iomx/libgstomx.so.p -Iomx -I../git/subprojects/gst-omx/omx -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/vcu2-omx-il -I. -I../git/subprojects/gst-omx -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/gstreamer-1.0 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/orc-0.4 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/glib-2.0 -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/lib/glib-2.0/include -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/lib/gstreamer-1.0/include -I/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Winit-self -Wmissing-include-dirs -Wno-multichar -Wvla -Wpointer-arith -Wundef -Wmissing-prototypes -Wold-style-definition -Waggregate-return -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/git/subprojects/gst-omx=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/git/subprojects/gst-omx=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/build=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/build=/usr/src/debug/gstreamer1.0-omx/1.22.12+git -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot= -fmacro-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot= -fdebug-prefix-map=/scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot-native= -fPIC -pthread -DHAVE_CONFIG_H -DGST_USE_UNSTABLE_API -MD -MQ omx/libgstomx.so.p/gstomxh265enc.c.o -MF omx/libgstomx.so.p/gstomxh265enc.c.o.d -o omx/libgstomx.so.p/gstomxh265enc.c.o -c ../git/subprojects/gst-omx/omx/gstomxh265enc.c
../git/subprojects/gst-omx/omx/gstomxh265enc.c: In function 'gst_omx_h265_enc_get_caps':
../git/subprojects/gst-omx/omx/gstomxh265enc.c:890:12: error: 'OMX_VIDEO_HEVCMainTierLevel63' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCMainTierLevel62'?
  890 |       case OMX_VIDEO_HEVCMainTierLevel63:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCMainTierLevel62
../git/subprojects/gst-omx/omx/gstomxh265enc.c:890:12: note: each undeclared identifier is reported only once for each function it appears in
../git/subprojects/gst-omx/omx/gstomxh265enc.c:894:12: error: 'OMX_VIDEO_HEVCMainTierLevel7' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCMainTierLevel6'?
  894 |       case OMX_VIDEO_HEVCMainTierLevel7:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCMainTierLevel6
../git/subprojects/gst-omx/omx/gstomxh265enc.c:898:12: error: 'OMX_VIDEO_HEVCMainTierLevel71' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCMainTierLevel61'?
  898 |       case OMX_VIDEO_HEVCMainTierLevel71:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCMainTierLevel61
../git/subprojects/gst-omx/omx/gstomxh265enc.c:902:12: error: 'OMX_VIDEO_HEVCMainTierLevel72' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCMainTierLevel62'?
  902 |       case OMX_VIDEO_HEVCMainTierLevel72:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCMainTierLevel62
../git/subprojects/gst-omx/omx/gstomxh265enc.c:938:12: error: 'OMX_VIDEO_HEVCHighTierLevel63' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCHighTierLevel3'?
  938 |       case OMX_VIDEO_HEVCHighTierLevel63:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCHighTierLevel3
../git/subprojects/gst-omx/omx/gstomxh265enc.c:942:12: error: 'OMX_VIDEO_HEVCHighTierLevel7' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCHighTierLevel3'?
  942 |       case OMX_VIDEO_HEVCHighTierLevel7:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCHighTierLevel3
../git/subprojects/gst-omx/omx/gstomxh265enc.c:946:12: error: 'OMX_VIDEO_HEVCHighTierLevel71' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCHighTierLevel31'?
  946 |       case OMX_VIDEO_HEVCHighTierLevel71:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCHighTierLevel31
../git/subprojects/gst-omx/omx/gstomxh265enc.c:950:12: error: 'OMX_VIDEO_HEVCHighTierLevel72' undeclared (first use in this function); did you mean 'OMX_VIDEO_HEVCHighTierLevel2'?
  950 |       case OMX_VIDEO_HEVCHighTierLevel72:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            OMX_VIDEO_HEVCHighTierLevel2
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/recipe-sysroot-native/usr/bin/ninja -j 32 -v
WARNING: /scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/temp/run.do_compile.3830376:153 exit 1 from 'meson compile -v -j 32'
WARNING: Backtrace (BB generated script):
	#1: meson_do_compile, /scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/temp/run.do_compile.3830376, line 153
	#2: do_compile, /scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/temp/run.do_compile.3830376, line 148
	#3: main, /scratch/sandeep/yocto/2025.1/yp-vnc-merge/build-sdt/tmp/work/versal2_common-basecamp-linux/gstreamer1.0-omx/1.22.12+git/temp/run.do_compile.3830376, line 157

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>