image_oci_microblaze: Skip any recipes that use image-oci
image-oci does not support riscv-32 and remove check for rv tunes.
We need to skip all recipe that use image-oci bbclass otherwise a
recent change to Poky/Oe-core triggers are parse error that looks
like:

ERROR: ExpansionError during parsing /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-virtualization/recipes-extended/images/container-app-base.bb                      | ETA:  0:00:40
bb.data_smart.ExpansionError: Failure expanding variable OCI_IMAGE_ARCH, expression was ${@oe.go.map_arch(d.getVar('TARGET_ARCH'))} which triggered exception KeyError: 'Cannot map architecture riscv32'
The variable dependency chain for the failure is: OCI_IMAGE_ARCH -> IMAGE_CMD:oci

ERROR: Parsing halted due to errors, see error messages above

ERROR: ExpansionError during parsing /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-virtualization/recipes-extended/images/container-systemd-base.bb                  | ETA:  0:01:09
bb.data_smart.ExpansionError: Failure expanding variable OCI_IMAGE_ARCH, expression was ${@oe.go.map_arch(d.getVar('TARGET_ARCH'))} which triggered exception KeyError: 'Cannot map architecture riscv32'
The variable dependency chain for the failure is: OCI_IMAGE_ARCH -> IMAGE_CMD:oci

ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260130021026.3811894-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>