u-boot-xlnx-arch-2026.1: Enable RISC-V compression ISA
Enable RISC-V compressed ISA support.

With SPI DM support enabled via xilinx_mbv_spi.config increases the SPL
image size and causes it to overflow the 64KB .spl_mem region on
MicroBlaze-V builds.

| riscv64-amd-linux-ld: u-boot-spl section `.data' will not fit in region `.spl_mem'
| riscv64-amd-linux-ld: section .bss VMA [000000000000f000,000000000000f0af] overlaps section .data VMA [000000000000e550,00000000000102ef]
| riscv64-amd-linux-ld: region `.spl_mem' overflowed by 8400 bytes
| make[2]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/git/scripts/Makefile.xpl:542: spl/u-boot-spl] Error 1
| make[1]: *** [/scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/git/Makefile:2376: spl/u-boot-spl] Error 2
| make[1]: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/build'
| make: *** [Makefile:198: sub-make] Error 2
| make: Leaving directory '/scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/git'
| ERROR: oe_runmake failed
| WARNING: /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244:281 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 281
| 	#2: die, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 265
| 	#3: oe_runmake, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 251
| 	#4: uboot_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 217
| 	#5: do_compile, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 178
| 	#6: main, /scratch/sandeep/yocto/2026.1/yp-edf/build-mbv/tmp/work/mbv64_sp701_sdt-amd-linux/u-boot-xlnx/2026.01-xilinx-v2026.1+git/temp/run.do_compile.3966244, line 294
ERROR: Task (/scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/u-boot/u-boot-xlnx_2026.01-xilinx-v2026.1.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1305 tasks of which 1198 didn't need to be rerun and 1 failed.

Fix this by adding u-boot-riscv-isa_c.cfg to SRC_URI_RISCV to enable
RISC-V compressed ISA support, reducing the SPL size. Also fix a
trailing newline issue.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20260324191022.2389606-3-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>