boot-jtag: Fix fpga-overlay typo
boot-jtag script had a type for fpga-overlay and due to this it fails
to build with below errors when fpga-overlay is enabled for zynqmp or
versal devices.

$ MACHINE=zynqmp-zcu104-sdt-full devtool boot-jtag --image core-image-full-cmdline --hw_server zcu104-5
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /scratch/sandeep/yocto/2024.2/yp-dev/build-yp-native/cache/prserv.sqlite3, Address: 127.0.0.1:33765, PID: 1586408
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#1)... (09:43:24.858854)
NOTE: Started PRServer with DBfile: /scratch/sandeep/yocto/2024.2/yp-dev/build-yp-native/cache/prserv.sqlite3, Address: 127.0.0.1:35749, PID: 1586439
Loading cache: 100% |###############################################################################################################################################################################| Time: 0:00:06
Loaded 26502 entries from dependency cache.
Parsing recipes: 100% |#############################################################################################################################################################################| Time: 0:00:02
Parsing of 18552 .bb files complete (18543 cached, 9 parsed). 26511 targets, 13521 skipped, 81 masked, 0 errors.
INFO: HW_SERVER Connected to: zcu104-5
INFO: Using DISTRO IMAGE: core-image-full-cmdline
INFO: SOC FAMILY: zynqmp
INFO: MACHINE: zynqmp-zcu104-sdt-full
INFO: fpga-overlay MACHINE_FEATURES is not enabled, Hence PL bitstream or PDI will be loaded at initial boot.
Traceback (most recent call last):
  File "/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/scripts/devtool", line 350, in <module>
    ret = main()
  File "/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/scripts/devtool", line 337, in main
    ret = args.func(args, config, basepath, workspace)
  File "/scratch/sandeep/yocto/2024.2/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/lib/devtool/boot-jtag.py", line 82, in bootjtag
    data['bit'] = glob.glob(os.path.join(deploy_dir, '*' + machine + '.bit'))[0]
IndexError: list index out of range

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>