embeddedsw-source: Fix circular references in xsct builds
Using external source method xsct embeddedsw firmware recipe fails to
build with do_configure task with circular refereces errors.

ERROR: plm-firmware-2025.1+git-r0 do_configure: ExecutionError('/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/temp/run.do_configure.875924', 134, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/temp/log.do_configure.875924
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx-tools/recipes-utils/xsct/xsct-native.bb:do_populate_sysroot', '/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/cmake/cmake-native_3.28.3.bb:do_populate_sysroot', '/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3-pyyaml_6.0.1.bb:do_populate_sysroot', 'virtual:native:/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/meta/recipes-devtools/python/python3_3.12.9.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['xsct-native', 'gettext-minimal-native', 'cmake-native', 'libtool-native', 'quilt-native', 'texinfo-dummy-native', 'libyaml-native', 'util-linux-libuuid-native', 'openssl-native', 'expat-native', 'ncurses-native', 'zlib-native', 'libedit-native', 'make-native', 'patch-native', 'perl-native', 'pseudo-native', 'python3-build-native', 'python3-cython-native', 'python3-flit-core-native', 'python3-installer-native', 'python3-packaging-native', 'python3-pyproject-hooks-native', 'python3-pyyaml-native', 'python3-setuptools-native', 'python3-wheel-native', 'python3-native', 'bzip2-native', 'libnsl2-native', 'libtirpc-native', 'unzip-native', 'xz-native', 'zstd-native', 'attr-native', 'gdbm-native', 'libffi-native', 'sqlite3-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| MISC_ARG is  -yamlconf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/plm-firmware.yaml
| APP_ARG is  -app "versal PLM"
| Using xsct from: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/recipe-sysroot-native/Vitis/2025.1/bin/xsct
| cmd is: xsct -sdx -nodisp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/app.tcl -ws /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/git/plm-firmware -pname plm-firmware -rp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/git -processor_ip psv_pmc -hdf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/deploy/images/vck190-versal/Xilinx-vck190-versal.xsa -arch 32   -app "versal PLM"  -yamlconf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/plm-firmware.yaml
|
| ****** Software Commandline Tool (XSCT) v2025.1.0
|   **** SW Build 6113974 on Wed Apr 23 16:20:36 MDT 2025
|     ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
|     ** Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
|
|
| Warning: XSCT is deprecated and will be removed in future releases.
| We recommend using the new Python command-line tool for project management and debugging:
| - Run "vitis -i" for interactive mode.
| - Run "vitis -s <script>" for script mode.
| WARNING: Failed in finding /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/recipe-sysroot-native/Vitis/2025.1/data/system-device-tree-xlnx/device_tree/data/device_tree.tcl path.
| WARNING: sdtgen package cannot be loaded. System Device tree commands will not
|
| be available
| INFO: [Hsi 55-2053] elapsed time for repository (/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/recipe-sysroot-native/Vitis/2025.1/data/embeddedsw) loading 0 seconds
| terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
|   what():  boost::filesystem::status: Too many levels of symbolic links: "/scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-workdir/git/oe-logs/log.do_configure"
| /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/recipe-sysroot-native/Vitis/2025.1/bin/rdiArgs.sh: line 454: 875990 Aborted                 (core dumped) "$RDI_PROG" "$@"
| WARNING: /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/temp/run.do_configure.875924:169 exit 134 from 'eval xsct -sdx -nodisp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/app.tcl -ws /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/git/plm-firmware -pname plm-firmware -rp /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/git -processor_ip psv_pmc -hdf /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/deploy/images/vck190-versal/Xilinx-vck190-versal.xsa -arch 32 ${APP_ARG} ${MISC_ARG}'
| WARNING: Backtrace (BB generated script):
| 	#1: do_configure, /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/temp/run.do_configure.875924, line 169
| 	#2: main, /scratch/sandeep/yocto/2025.1/yp-dev/build-versal/tmp/work/vck190_versal-amd-linux/plm-firmware/2025.1+git/temp/run.do_configure.875924, line 173
ERROR: Task (/scratch/sandeep/yocto/2025.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-standalone/recipes-bsp/embeddedsw/plm-firmware_2025.1.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 872 tasks of which 867 didn't need to be rerun and 1 failed.

This is due to external source symlinks are copied from
embeddedsw-source to firmware destination directory. Hence remove the
external source symlinks in destination directory once copy is done.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>