embeddedsw: Add mmidp driver recipe
versal-2ve-2vm plmfw fails to build with below errors

ERROR: Nothing PROVIDES 'mmidp' (but mc:versal-2ve-2vm-vek385-sdt-seg-microblaze-pmc:/scratch/sandeep/yocto/2025.1/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-standalone-sdt/recipes-libraries/embeddedsw/libxil_2025.1.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'plm-firmware' has no buildable providers.
Missing or unbuildable dependency chain was: ['plm-firmware', 'xilpm-ng', 'libxil', 'mmidp']

This is due to versal-2ve-2vm plmfw depends on mmidp drivers.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>