u-boot-xen-scr: Fix compile errors with native packgage
u-boot-xen-scr do_compile errors are observed with native package.

ERROR: u-boot-xen-scr-1.0-r0 do_compile: ExecutionError('/scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/run.do_compile.774804', 127, None, None)
ERROR: Logfile of failure stored in: /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/log.do_compile.774804
Log data follows:
| DEBUG: Executing shell function do_compile
| /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/run.do_compile.774804: line 140: /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/deploy/images/amd-cortexa72-common/scripts/uboot-script-gen: No such file or directory
| WARNING: /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/run.do_compile.774804:140 exit 127 from '/scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/deploy/images/amd-cortexa72-common/scripts/uboot-script-gen -c /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/u-boot-xen-scr-dom0-template-cfg -s -d /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0 -o /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/xen_boot'
| WARNING: Backtrace (BB generated script):
| 	#1: do_compile, /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/run.do_compile.774804, line 140
| 	#2: main, /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/run.do_compile.774804, line 144
ERROR: Task (/scratch/sandeep/yocto/2025.2/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-virtualization/recipes-bsp/u-boot/u-boot-xen-scr.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1127 tasks of which 1123 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /scratch/sandeep/yocto/2025.2/yp-edf/sources/poky/../meta-xilinx/meta-xilinx-virtualization/recipes-bsp/u-boot/u-boot-xen-scr.bb:do_compile
    log: /scratch/sandeep/yocto/2025.2/yp-edf/build-versal/tmp/work/amd_cortexa72_common-amd-linux/u-boot-xen-scr/1.0/temp/log.do_compile.774804
Summary: There were 2 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

Hence add do_compile depends on image builder sysroot-native task.
Also use recpie-sysroot-native path tools to compile instead of
DEPLOY_DIR_IMAGE path.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>