meta-microblaze: Skip any recipes that use go
go does not support microblaze.  We need to skip all recipe that use go
otherwise a recent change to Poky/Oe-core triggers are parse error that
looks like:

  WARNING: <recipe>: Exception during build_dependencies for GOARCH
  WARNING: <recipe>: Error during finalise of mc:<multiconfig>:<recipe>
  ERROR: ExpansionError during parsing <recipe>
  bb.data_smart.ExpansionError: Failure expanding variable TARGET_GOARCH, expression was ${@go_map_arch(d.getVar('TARGET_ARCH'), d)} which triggered exception KeyError: 'Cannot map architecture microblazeel'
  The variable dependency chain for the failure is: TARGET_GOARCH -> GOARCH

  ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Message-Id: <20251127005244.3509066-1-mark.hatle@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>