Revert "meta-xilinx-standalone : xlnx-embeddedsw : Updated SRCREV for 2026.1_5403"
This reverts commit 5eff1043f91e4836d435e696dc4eaf521e2955fe.

This breaks the image-selector with the error:
image-selector/src/versal/xis_module.c: In function 'XPlm_ModuleInit':
image-selector/1.0+git/image-selector/src/versal/xis_module.c:65:18: error: too few arguments to function 'XPlmi_Init'
   65 |         Status = XPlmi_Init()

Signed-off-by: Mark Hatle <mark.hatle@amd.com>