meta-microblaze: Skip any recipes that use image-oci
image-oci does not support riscv-32 and microblaze. We need to skip all
recipe that use image-oci bbclass otherwise a recent change to
Poky/Oe-core triggers are parse error that looks like:

NOTE: Started PRServer with DBfile: /scratch/sandeep/yocto/2026.1/yp-edf/build-mb-v/cache/prserv.sqlite3, Address: 127.0.0.1:40769, PID: 988585
Loading cache: 100% |                                                                                                                                                                              | ETA:  --:--:--
Loaded 0 entries from dependency cache.
ERROR: ExpansionError during parsing /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-virtualization/recipes-extended/images/container-base.bb                                             | ETA:  0:00:39
bb.data_smart.ExpansionError: Failure expanding variable OCI_IMAGE_ARCH, expression was ${@oe.go.map_arch(d.getVar('TARGET_ARCH'))} which triggered exception KeyError: 'Cannot map architecture riscv32'
The variable dependency chain for the failure is: OCI_IMAGE_ARCH -> IMAGE_CMD:oci

ERROR: Parsing halted due to errors, see error messages above

NOTE: Started PRServer with DBfile: /scratch/sandeep/yocto/2026.1/yp-edf/build-mb-v/cache/prserv.sqlite3, Address: 127.0.0.1:40769, PID: 988585
Loading cache: 100% |                                                                                                                                                                              | ETA:  --:--:--
Loaded 0 entries from dependency cache.
ERROR: ExpansionError during parsing /scratch/sandeep/yocto/2026.1/yp-edf/sources/poky/../meta-virtualization/recipes-extended/images/container-base.bb                                             | ETA:  0:00:56
bb.data_smart.ExpansionError: Failure expanding variable OCI_IMAGE_ARCH, expression was ${@oe.go.map_arch(d.getVar('TARGET_ARCH'))} which triggered exception KeyError: 'Cannot map architecture microblazeel'
The variable dependency chain for the failure is: OCI_IMAGE_ARCH -> IMAGE_CMD:oci

ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Message-ID: <20251201222849.1921391-1-sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>